# Configuração oficial do botão "Sponsor" no GitHub

# Substitua com seus respectivos usuários ou links de doação:
github: # Seu nome de usuário do GitHub (ex: mauricio)
ko_fi: # Seu usuário do Ko-fi (ex: mauricio)
patreon: # Seu usuário do Patreon (ex: mauricio)

# Link customizado (perfeito para Pix ou link do PayPal)
custom: ['https://github.com/mauriciominas/SmartDev-Installer#apoie-o-projeto-doação--support-the-project']
